# Generated by Django 4.0.6 on 2022-07-26 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.IntegerField()),
                ('dosage_unit', models.CharField(choices=[('Drop', 'Drop'), ('Pill', 'Pill'), ('Tablet', 'Tablet'), ('Vial', 'Vial'), ('Others', 'Others')], default='DROP', max_length=100)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='DAILY', max_length=100)),
                ('frequency_unit', models.CharField(choices=[('Once', 'Once'), ('Twice', 'Twice'), ('Trice', 'Trice'), ('Others', 'Others')], default='ONCE', max_length=100)),
                ('created_at', models.DateTimeField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
